services:
  web:
    build:
      context: .
      target: production
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-}
        SUPABASE_PUBLIC_ANON: ${VITE_SUPABASE_ANON_KEY:-}
        BUILD_MODE: participant
        VITE_ADMIN_BASE_URL: ${VITE_ADMIN_BASE_URL:-}
    ports:
      - "5173:80"

  admin:
    build:
      context: .
      target: production
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-}
        SUPABASE_PUBLIC_ANON: ${VITE_SUPABASE_ANON_KEY:-}
        BUILD_MODE: admin
        VITE_ADMIN_BASE_URL: ${VITE_ADMIN_BASE_URL:-}
    ports:
      - "5174:80"
